local papagaio_md = {}

-- Helper to trim whitespace
local function trim(s)
    return s:match("^%s*(.-)%s*$")
end

function papagaio_md.parse(text)
    local root = {}
    local stack = { {node = root, depth = 0} }

    local lines = {}
    for line in text:gmatch("([^\r\n]*)\r?\n?") do
        -- avoid empty match at end of string
        if #lines == 0 or line ~= "" or #text > 0 then
            table.insert(lines, line)
        end
    end
    -- remove last empty line if generated by gmatch
    if #lines > 0 and lines[#lines] == "" then
        table.remove(lines)
    end

    local i = 1
    while i <= #lines do
        local line = lines[i]

        -- Heading
        local h_match, h_text = line:match("^(#+)%s*(.*)")
        if h_match then
            local depth = #h_match
            local title = trim(h_text)

            -- pop stack until we find a parent level
            while #stack > 0 and stack[#stack].depth >= depth do
                table.remove(stack)
            end

            local new_node = {}
            local parent = stack[#stack].node

            -- If parent is an array (paragraphs), we can't easily set string keys.
            -- But paragraphs are pushed without keys in the sequence part, and headings are named keys.
            parent[title] = new_node

            table.insert(stack, {node = new_node, depth = depth})
            i = i + 1

        -- Table
        elseif line:match("^%s*|.*|%s*$") then
            local table_data = {}
            -- parse consecutive table rows
            while i <= #lines do
                local tline = lines[i]
                if not tline:match("^%s*|.*|%s*$") then break end

                local row = {}
                -- string split by |
                -- skip first empty match before first | and last empty match after last |
                local cols = {}
                for col in tline:gmatch("|([^|]*)") do
                    table.insert(cols, trim(col))
                end

                -- remove last element if it's empty due to ending |
                if #cols > 0 and cols[#cols] == "" then
                    table.remove(cols)
                end

                -- check if it's a separator row (---)
                local is_sep = true
                for _, cell in ipairs(cols) do
                    if cell ~= "" and not cell:match("^%-+$") and not cell:match("^:%-+$") and not cell:match("^%-+:$") and not cell:match("^:%-+:$") then
                        is_sep = false
                        break
                    end
                end

                if not is_sep then
                    -- convert to number if possible
                    local parsed_row = {}
                    for _, cell in ipairs(cols) do
                        local num = tonumber(cell)
                        if num then
                            table.insert(parsed_row, num)
                        else
                            table.insert(parsed_row, cell)
                        end
                    end
                    table.insert(table_data, parsed_row)
                end
                i = i + 1
            end

            local parent = stack[#stack].node
            table.insert(parent, table_data)

        -- Skip code blocks entirely for tree content?
        -- The user said "resto tudo vira strings e dividido em parágrafos", but usually code blocks shouldn't be parsed or they should be a single text chunk.
        -- Let's extract code blocks as single paragraphs.
        elseif line:match("^%s*```") then
            local fence = line:match("^%s*(```+)")
            local code_lines = { line }
            i = i + 1
            while i <= #lines do
                local cline = lines[i]
                table.insert(code_lines, cline)
                i = i + 1
                if cline:match("^%s*" .. fence) then
                    break
                end
            end
            local parent = stack[#stack].node
            table.insert(parent, table.concat(code_lines, "\n"))

        -- Blank lines
        elseif line:match("^%s*$") then
            i = i + 1

        -- Normal paragraph
        else
            local p_lines = {}
            while i <= #lines do
                local pline = lines[i]
                if pline:match("^%s*$") or pline:match("^(#+)%s*") or pline:match("^%s*|.*|%s*$") or pline:match("^%s*```") then
                    break
                end
                table.insert(p_lines, pline)
                i = i + 1
            end
            local parent = stack[#stack].node
            table.insert(parent, table.concat(p_lines, "\n"))
        end
    end

    return root
end

function papagaio_md.execute_blocks(text)
    local env = _G
    for code in text:gmatch("```lua\n(.-)```") do
        local chunk, err = load(code, "markdown_block", "t", env)
        if chunk then
            local ok, run_err = pcall(chunk)
            if not ok then
                print("[ERROR] lua block execution failed: " .. tostring(run_err))
            end
        else
            print("[ERROR] lua block syntax error: " .. tostring(err))
        end
    end
end

function papagaio_md.run(text)
    _G.global = _G.global or {}
    _G.global.md = papagaio_md.parse(text)
    papagaio_md.execute_blocks(text)
end

return papagaio_md
